version: '2'
services:
    wildfly: 
        build: images/wildfly
        ports:
            - "9090:8080"
            - "9990:9990"
        links:
            - mysql:db
    mysql:
        build: images/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        environment:
            - MYSQL_ROOT_PASSWORD=root
        ports:
            - "6060:80"
        links:
            - mysql:db
