version: '3.7'

services:

  payara:
    build: images_docker/payara
    environment:
      PAYARA_ARGS: "--debug"
    ports:
      - 8080:8080
      - 4848:4848
      - 9009:9009
  db:
    build: images_docker/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: amt_project_one
      MYSQL_ROOT_PASSWORD: bananaSplat

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=db
    restart: always
    depends_on:
      - db
    ports:
      - 6060:80

